version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: voiceflow_pro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - voiceflow-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    networks:
      - voiceflow-network

  # LiveKit Server
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    depends_on:
      - redis
    networks:
      - voiceflow-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/voiceflow_pro
      - LIVEKIT_URL=wss://voiceflow-pro-1ekj4ijn.livekit.cloud
      - LIVEKIT_API_KEY=xyz
      - LIVEKIT_API_SECRET=xyz
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - voiceflow-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_LIVEKIT_URL=wss://voiceflow-pro-1ekj4ijn.livekit.cloud
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - voiceflow-network

  # Python Agents
  agents:
    build:
      context: ./agents
      dockerfile: Dockerfile
    environment:
      - LIVEKIT_URL=wss://voiceflow-pro-1ekj4ijn.livekit.cloud
      - LIVEKIT_API_KEY=xyz
      - LIVEKIT_API_SECRET=xyz
      - ASSEMBLYAI_API_KEY=xyz
      - OPENAI_API_KEY=xyz      - ELEVENLABS_API_KEY=xyz
    depends_on:
      - postgres
      - redis
    volumes:
      - ./agents:/app
    networks:
      - voiceflow-network

volumes:
  postgres_data:

networks:
  voiceflow-network:
    driver: bridge